/**
 * Board generator — reads issue frontmatter and produces BOARD.md content.
 *
 * This is the TypeScript replacement for scripts/generate-board.py.
 * It uses the frontmatter `status` field as source of truth,
 * with a warning if the file's folder doesn't match.
 */

import { readdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import { parseFrontmatter, type Frontmatter } from "./frontmatter.js";

export interface Issue {
  frontmatter: Frontmatter;
  filename: string;
  folder: string;
  /** Status from frontmatter (source of truth) */
  status: string;
}

export interface BoardData {
  issues: Issue[];
  warnings: string[];
  nextNumber: string;
}

const STATUS_FOLDERS = [
  "0-icebox",
  "1-backlog",
  "2-sprint",
  "3-in-progress",
  "4-review",
  "5-done",
];

const STATUS_LABELS: Record<string, string> = {
  "0-icebox": "ideas",
  "1-backlog": "prioritized",
  "2-sprint": "committed",
  "3-in-progress": "in dev",
  "4-review": "review/test",
  "5-done": "completed",
};

/**
 * Scans the issue-board directory and collects all issues with their frontmatter.
 */
export function collectIssues(boardDir: string): BoardData {
  const issues: Issue[] = [];
  const warnings: string[] = [];
  let maxNum = 0;

  for (const folder of STATUS_FOLDERS) {
    const folderPath = join(boardDir, folder);
    if (!existsSync(folderPath)) continue;

    const files = readdirSync(folderPath)
      .filter((f) => f.startsWith("ISS-") && f.endsWith(".md"))
      .sort();

    for (const file of files) {
      const content = readFileSync(join(folderPath, file), "utf-8");
      const fm = parseFrontmatter(content);

      if (!fm) {
        warnings.push(`${folder}/${file}: no YAML frontmatter found`);
        continue;
      }

      // Frontmatter status is the source of truth
      const fmStatus = typeof fm.status === "string" ? fm.status : "";
      if (fmStatus && fmStatus !== folder) {
        warnings.push(
          `${folder}/${file}: folder is ${folder} but frontmatter says status: ${fmStatus}`
        );
      }

      issues.push({
        frontmatter: fm,
        filename: file,
        folder,
        status: fmStatus || folder,
      });

      // Track highest issue number for "next number"
      const numMatch = file.match(/ISS-(\d+)/);
      if (numMatch) {
        maxNum = Math.max(maxNum, parseInt(numMatch[1], 10));
      }
    }
  }

  const nextNumber = `ISS-${String(maxNum + 1).padStart(4, "0")}`;

  return { issues, warnings, nextNumber };
}

/**
 * Generates the BOARD.md content from collected issues.
 */
export function generateBoardMarkdown(data: BoardData): string {
  const today = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push("# Issue Board");
  lines.push("");
  lines.push(
    "> This file is generated by `lytos board`. The source of truth is the YAML frontmatter of each issue."
  );
  lines.push(">");
  lines.push(`> **Last generated**: ${today}`);
  lines.push(`> **Next number**: ${data.nextNumber}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Issue index");
  lines.push("");

  for (const folder of STATUS_FOLDERS) {
    const label = STATUS_LABELS[folder];
    lines.push(`### ${folder} (${label})`);
    lines.push("");

    const folderIssues = data.issues.filter((i) => i.status === folder);

    if (folderIssues.length === 0) {
      lines.push("_No issues._");
      lines.push("");
      continue;
    }

    if (folder === "5-done") {
      lines.push("| # | Title | Completed |");
      lines.push("|---|-------|-----------|");
      for (const issue of folderIssues) {
        const id = issue.frontmatter.id || "?";
        const title = issue.frontmatter.title || "?";
        const updated = issue.frontmatter.updated || "?";
        const relPath = `${issue.folder}/${issue.filename}`;
        lines.push(`| [${id}](${relPath}) | ${title} | ${updated} |`);
      }
    } else {
      // Check if any issue has depends
      const hasDeps = folderIssues.some((i) => {
        const deps = i.frontmatter.depends;
        return Array.isArray(deps) ? deps.length > 0 : !!deps;
      });

      if (hasDeps) {
        lines.push("| # | Title | Priority | Effort | Depends |");
        lines.push("|---|-------|----------|--------|---------|");
      } else {
        lines.push("| # | Title | Priority | Effort |");
        lines.push("|---|-------|----------|--------|");
      }

      for (const issue of folderIssues) {
        const id = issue.frontmatter.id || "?";
        const title = issue.frontmatter.title || "?";
        const priority = issue.frontmatter.priority || "?";
        const effort = issue.frontmatter.effort || "?";
        const relPath = `${issue.folder}/${issue.filename}`;

        if (hasDeps) {
          const deps = issue.frontmatter.depends;
          const depsStr = Array.isArray(deps) && deps.length > 0
            ? deps.join(", ")
            : "—";
          lines.push(
            `| [${id}](${relPath}) | ${title} | ${priority} | ${effort} | ${depsStr} |`
          );
        } else {
          lines.push(
            `| [${id}](${relPath}) | ${title} | ${priority} | ${effort} |`
          );
        }
      }
    }

    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by `lytos board` — the YAML frontmatter is the source of truth.*"
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Converts collected board data to a JSON-friendly structure.
 */
export function boardToJson(
  data: BoardData
): Record<string, unknown> {
  return {
    generated: new Date().toISOString().slice(0, 10),
    nextNumber: data.nextNumber,
    warnings: data.warnings,
    columns: STATUS_FOLDERS.map((folder) => ({
      folder,
      label: STATUS_LABELS[folder],
      issues: data.issues
        .filter((i) => i.status === folder)
        .map((i) => ({
          id: i.frontmatter.id,
          title: i.frontmatter.title,
          priority: i.frontmatter.priority,
          effort: i.frontmatter.effort,
          complexity: i.frontmatter.complexity,
          depends: i.frontmatter.depends,
          status: i.status,
          file: `${i.folder}/${i.filename}`,
        })),
    })),
  };
}
