/**
 * Board generator — reads issue frontmatter and produces BOARD.md content.
 *
 * This is the TypeScript replacement for scripts/generate-board.py.
 * It uses the frontmatter `status` field as source of truth,
 * with a warning if the file's folder doesn't match.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync, renameSync } from "fs";
import { join } from "path";
import { parseFrontmatter, type Frontmatter } from "./frontmatter.js";

export interface Issue {
  frontmatter: Frontmatter;
  filename: string;
  folder: string;
  /** Status from frontmatter (source of truth) */
  status: string;
}

export interface BoardData {
  issues: Issue[];
  warnings: string[];
  nextNumber: string;
}

const STATUS_FOLDERS = [
  "0-icebox",
  "1-backlog",
  "2-sprint",
  "3-in-progress",
  "4-review",
  "5-done",
];

const STATUS_LABELS: Record<string, string> = {
  "0-icebox": "ideas",
  "1-backlog": "prioritized",
  "2-sprint": "committed",
  "3-in-progress": "in dev",
  "4-review": "review/test",
  "5-done": "recently completed",
};

interface ArchivedIssue {
  id: string;
  title: string;
  tags: string[];
  completed: string;
  quarter: string;
}

function dateToQuarter(dateStr: string): string {
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) {
    const now = new Date();
    const q = Math.ceil((now.getMonth() + 1) / 3);
    return `${now.getFullYear()}-Q${q}`;
  }
  const q = Math.ceil((date.getMonth() + 1) / 3);
  return `${date.getFullYear()}-Q${q}`;
}

function readArchiveIndex(archiveDir: string): ArchivedIssue[] {
  const indexPath = join(archiveDir, "INDEX.md");
  if (!existsSync(indexPath)) return [];

  const content = readFileSync(indexPath, "utf-8");
  const issues: ArchivedIssue[] = [];

  for (const line of content.split("\n")) {
    const match = line.match(/^\|\s*(ISS-\d+)\s*\|([^|]+)\|([^|]*)\|([^|]+)\|([^|]+)\|/);
    if (!match) continue;
    issues.push({
      id: match[1].trim(),
      title: match[2].trim(),
      tags: match[3].trim().split(",").map(t => t.trim()).filter(Boolean),
      completed: match[4].trim(),
      quarter: match[5].trim(),
    });
  }
  return issues;
}

function writeArchiveIndex(archiveDir: string, issues: ArchivedIssue[]): void {
  const lines = [
    "# Archive Index",
    "",
    "| # | Title | Tags | Completed | Quarter |",
    "|---|-------|------|-----------|---------|",
    ...issues
      .sort((a, b) => a.id.localeCompare(b.id))
      .map(i => `| ${i.id} | ${i.title} | ${i.tags.join(", ")} | ${i.completed} | ${i.quarter} |`),
    "",
    "*Generated by `lyt board`.*",
    "",
  ];
  mkdirSync(archiveDir, { recursive: true });
  writeFileSync(join(archiveDir, "INDEX.md"), lines.join("\n"), "utf-8");
}

export interface ArchiveOptions {
  /**
   * Only archive issues whose `updated` date is at least this many days old.
   * Defaults to `Infinity` (archive nothing) so callers must opt in explicitly.
   * The `lyt archive` command passes `7` by default; `--all` / `--older-than 0d`
   * passes `0` to archive everything.
   */
  olderThanDays?: number;
  /** Preview only — do not move files or write the index. */
  dryRun?: boolean;
}

export interface ArchiveMove {
  id: string;
  ageDays: number;
  quarter: string;
}

export interface ArchiveResult {
  moved: ArchiveMove[];
  skippedTooRecent: Array<{ id: string; ageDays: number }>;
}

function daysBetween(fromISO: string, today: Date): number {
  const from = new Date(fromISO + "T00:00:00Z");
  if (Number.isNaN(from.getTime())) return 0;
  const diffMs = today.getTime() - from.getTime();
  return Math.floor(diffMs / 86_400_000);
}

export function archiveIssues(
  boardDir: string,
  options: ArchiveOptions = {}
): ArchiveResult {
  const result: ArchiveResult = { moved: [], skippedTooRecent: [] };
  const doneDir = join(boardDir, "5-done");
  const archiveDir = join(boardDir, "archive");

  if (!existsSync(doneDir)) return result;

  const files = readdirSync(doneDir)
    .filter(f => f.startsWith("ISS-") && f.endsWith(".md"))
    .sort();

  if (files.length === 0) return result;

  const existing = readArchiveIndex(archiveDir);
  const existingIds = new Set(existing.map(i => i.id));
  const newEntries: ArchivedIssue[] = [];
  const olderThanDays = options.olderThanDays ?? Infinity;
  const today = new Date();

  for (const file of files) {
    const srcPath = join(doneDir, file);
    const content = readFileSync(srcPath, "utf-8");
    const fm = parseFrontmatter(content);
    if (!fm) continue;

    const id = typeof fm.id === "string" ? fm.id : file.replace(".md", "");
    if (existingIds.has(id)) continue;

    const completed = typeof fm.updated === "string" ? fm.updated : new Date().toISOString().slice(0, 10);
    const ageDays = daysBetween(completed, today);

    if (ageDays < olderThanDays) {
      result.skippedTooRecent.push({ id, ageDays });
      continue;
    }

    const quarter = dateToQuarter(completed);
    const title = typeof fm.title === "string" ? fm.title : "?";
    const tags = Array.isArray(fm.tags) ? fm.tags : [];

    if (!options.dryRun) {
      const quarterDir = join(archiveDir, quarter);
      mkdirSync(quarterDir, { recursive: true });
      renameSync(srcPath, join(quarterDir, file));
    }

    newEntries.push({ id, title, tags, completed, quarter });
    result.moved.push({ id, ageDays, quarter });
  }

  if (!options.dryRun && newEntries.length > 0) {
    writeArchiveIndex(archiveDir, [...existing, ...newEntries]);
  }

  return result;
}

export function countArchived(boardDir: string): number {
  const archiveDir = join(boardDir, "archive");
  return readArchiveIndex(archiveDir).length;
}

/** Highest ISS number in archive/INDEX.md (0 if none). */
function maxArchivedNumber(boardDir: string): number {
  const archiveDir = join(boardDir, "archive");
  let max = 0;
  for (const entry of readArchiveIndex(archiveDir)) {
    const m = entry.id.match(/ISS-(\d+)/);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  return max;
}

/**
 * Scans the issue-board directory and collects all issues with their frontmatter.
 */
export function collectIssues(boardDir: string): BoardData {
  const issues: Issue[] = [];
  const warnings: string[] = [];
  let maxNum = 0;

  for (const folder of STATUS_FOLDERS) {
    const folderPath = join(boardDir, folder);
    if (!existsSync(folderPath)) continue;

    const files = readdirSync(folderPath)
      .filter((f) => f.startsWith("ISS-") && f.endsWith(".md"))
      .sort();

    for (const file of files) {
      const content = readFileSync(join(folderPath, file), "utf-8");
      const fm = parseFrontmatter(content);

      if (!fm) {
        warnings.push(`${folder}/${file}: no YAML frontmatter found`);
        continue;
      }

      // Frontmatter status is the source of truth
      const fmStatus = typeof fm.status === "string" ? fm.status : "";
      if (fmStatus && fmStatus !== folder) {
        warnings.push(
          `${folder}/${file}: folder is ${folder} but frontmatter says status: ${fmStatus}`
        );
      }

      issues.push({
        frontmatter: fm,
        filename: file,
        folder,
        status: fmStatus || folder,
      });

      // Track highest issue number for "next number"
      const numMatch = file.match(/ISS-(\d+)/);
      if (numMatch) {
        maxNum = Math.max(maxNum, parseInt(numMatch[1], 10));
      }
    }
  }

  const archivedMax = maxArchivedNumber(boardDir);
  const globalMax = Math.max(maxNum, archivedMax);
  const nextNumber = `ISS-${String(globalMax + 1).padStart(4, "0")}`;

  return { issues, warnings, nextNumber };
}

/**
 * Generates the BOARD.md content from collected issues.
 */
export function generateBoardMarkdown(data: BoardData, archivedCount = 0): string {
  const today = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push("# Issue Board");
  lines.push("");
  lines.push(
    "> This file is generated by `lytos board`. The source of truth is the YAML frontmatter of each issue."
  );
  lines.push(">");
  lines.push(`> **Last generated**: ${today}`);
  lines.push(`> **Next number**: ${data.nextNumber}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Issue index");
  lines.push("");

  for (const folder of STATUS_FOLDERS) {
    const label = STATUS_LABELS[folder];
    lines.push(`### ${folder} (${label})`);
    lines.push("");

    const folderIssues = data.issues.filter((i) => i.status === folder);

    if (folderIssues.length === 0) {
      lines.push("_No issues._");
      lines.push("");
      continue;
    }

    if (folder === "5-done") {
      lines.push("| # | Title | Completed |");
      lines.push("|---|-------|-----------|");
      for (const issue of folderIssues) {
        const id = issue.frontmatter.id || "?";
        const title = issue.frontmatter.title || "?";
        const updated = issue.frontmatter.updated || "?";
        const relPath = `${issue.folder}/${issue.filename}`;
        lines.push(`| [${id}](${relPath}) | ${title} | ${updated} |`);
      }
    } else {
      // Check if any issue has depends
      const hasDeps = folderIssues.some((i) => {
        const deps = i.frontmatter.depends;
        return Array.isArray(deps) ? deps.length > 0 : !!deps;
      });

      if (hasDeps) {
        lines.push("| # | Title | Priority | Effort | Depends |");
        lines.push("|---|-------|----------|--------|---------|");
      } else {
        lines.push("| # | Title | Priority | Effort |");
        lines.push("|---|-------|----------|--------|");
      }

      for (const issue of folderIssues) {
        const id = issue.frontmatter.id || "?";
        const title = issue.frontmatter.title || "?";
        const priority = issue.frontmatter.priority || "?";
        const effort = issue.frontmatter.effort || "?";
        const relPath = `${issue.folder}/${issue.filename}`;

        if (hasDeps) {
          const deps = issue.frontmatter.depends;
          const depsStr = Array.isArray(deps) && deps.length > 0
            ? deps.join(", ")
            : "—";
          lines.push(
            `| [${id}](${relPath}) | ${title} | ${priority} | ${effort} | ${depsStr} |`
          );
        } else {
          lines.push(
            `| [${id}](${relPath}) | ${title} | ${priority} | ${effort} |`
          );
        }
      }
    }

    lines.push("");
  }

  // Archive summary
  lines.push("### Archive");
  lines.push("");
  if (archivedCount > 0) {
    lines.push(`${archivedCount} issues archived → [archive/INDEX.md](archive/INDEX.md)`);
  } else {
    lines.push("_No archived issues yet._");
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by `lytos board` — the YAML frontmatter is the source of truth.*"
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Converts collected board data to a JSON-friendly structure.
 */
export function boardToJson(
  data: BoardData
): Record<string, unknown> {
  return {
    generated: new Date().toISOString().slice(0, 10),
    nextNumber: data.nextNumber,
    warnings: data.warnings,
    columns: STATUS_FOLDERS.map((folder) => ({
      folder,
      label: STATUS_LABELS[folder],
      issues: data.issues
        .filter((i) => i.status === folder)
        .map((i) => ({
          id: i.frontmatter.id,
          title: i.frontmatter.title,
          priority: i.frontmatter.priority,
          effort: i.frontmatter.effort,
          complexity: i.frontmatter.complexity,
          depends: i.frontmatter.depends,
          status: i.status,
          file: `${i.folder}/${i.filename}`,
        })),
    })),
  };
}
