/**
 * Scaffolding logic for `lytos init`.
 *
 * Creates the .lytos/ directory structure and all essential files.
 * Downloads skills, rules, and LYTOS.md from the Lytos GitHub repo.
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  manifestTemplate,
  memoryTemplate,
  cortexTemplate,
  getCortexFiles,
  boardTemplate,
  claudeTemplate,
  codexTemplate,
  cursorrTemplate,
  copilotTemplate,
  geminiTemplate,
  windsurfTemplate,
} from "./templates.js";
import type { DetectedStack } from "./detect-stack.js";
import { installPreCommitHook } from "./hooks.js";

const METHOD_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "method"
);

// session-start is a Lytos bootstrap protocol, kept as a flat file at
// .lytos/skills/session-start.md and read at the start of every session.
const SESSION_SKILL = "session-start";

// Task skills follow the agentskills.io format: a folder containing a
// SKILL.md with `name` + `description` frontmatter. Loaded on demand by
// the AI tool's native skill discovery.
const TASK_SKILLS = [
  "code-review",
  "testing",
  "documentation",
  "git-workflow",
  "code-structure",
  "deployment",
  "security",
  "api-design",
];

const REMOTE_FILES = [
  { remote: `skills/${SESSION_SKILL}.md`, local: `skills/${SESSION_SKILL}.md` },
  ...TASK_SKILLS.map((s) => ({
    remote: `skills/${s}/SKILL.md`,
    local: `skills/${s}/SKILL.md`,
  })),
  { remote: "rules/default-rules.md", local: "rules/default-rules.md" },
  { remote: "rules/README.md", local: "rules/README.md" },
  { remote: "LYTOS.md", local: "LYTOS.md" },
  // Gitignore that protects 6-private-notes/ from accidental commits
  { remote: ".gitignore", local: ".gitignore" },
  { remote: "templates/sprint.md", local: "templates/sprint.md" },
  {
    remote: "issue-board/templates/issue-feature.md",
    local: "issue-board/templates/issue-feature.md",
  },
  {
    remote: "issue-board/templates/issue-task.md",
    local: "issue-board/templates/issue-task.md",
  },
];

export type LytosTool =
  | "claude"
  | "cursor"
  | "codex"
  | "copilot"
  | "gemini"
  | "windsurf"
  | "none";

export interface ScaffoldOptions {
  projectName: string;
  tool: LytosTool;
  lang: "en" | "fr";
  profile: "vibe-coder" | "developer" | "lead";
  stack: Partial<DetectedStack>;
  cwd: string;
  dryRun: boolean;
}

export interface ScaffoldResult {
  filesCreated: string[];
  filesSkipped: string[];
  warnings: string[];
}

function readBundled(relativePath: string): string {
  return readFileSync(join(METHOD_DIR, relativePath), "utf-8");
}

function ensureDir(dir: string, dryRun: boolean): void {
  if (!dryRun && !existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function writeFile(
  path: string,
  content: string,
  dryRun: boolean,
  result: ScaffoldResult
): void {
  if (dryRun) {
    result.filesCreated.push(path);
    return;
  }
  ensureDir(join(path, ".."), false);
  writeFileSync(path, content, "utf-8");
  result.filesCreated.push(path);
}

export function scaffold(options: ScaffoldOptions): ScaffoldResult {
  const result: ScaffoldResult = {
    filesCreated: [],
    filesSkipped: [],
    warnings: [],
  };

  const lytosDir = join(options.cwd, ".lytos");
  const today = new Date().toISOString().slice(0, 10);
  const ctx = {
    projectName: options.projectName,
    date: today,
    stack: options.stack,
    lang: options.lang,
  };

  // Create directory structure
  const dirs = [
    "memory/cortex",
    "rules",
    "skills",
    "scripts",
    "templates",
    "issue-board/0-icebox",
    "issue-board/1-backlog",
    "issue-board/2-sprint",
    "issue-board/3-in-progress",
    "issue-board/4-review",
    "issue-board/5-done",
    "issue-board/6-private-notes",
    "issue-board/archive",
    "issue-board/templates",
  ];

  for (const dir of dirs) {
    ensureDir(join(lytosDir, dir), options.dryRun);
  }

  // Create .gitkeep files in empty Kanban folders
  const kanbanDirs = [
    "0-icebox",
    "1-backlog",
    "2-sprint",
    "3-in-progress",
    "4-review",
    "5-done",
    "6-private-notes",
  ];
  for (const dir of kanbanDirs) {
    writeFile(
      join(lytosDir, "issue-board", dir, ".gitkeep"),
      "",
      options.dryRun,
      result
    );
  }

  // Generate local files from templates
  writeFile(
    join(lytosDir, "manifest.md"),
    manifestTemplate(ctx),
    options.dryRun,
    result
  );
  writeFile(
    join(lytosDir, "memory", "MEMORY.md"),
    memoryTemplate(ctx),
    options.dryRun,
    result
  );
  writeFile(
    join(lytosDir, "issue-board", "BOARD.md"),
    boardTemplate(ctx),
    options.dryRun,
    result
  );
  writeFile(
    join(lytosDir, "issue-board", "archive", "INDEX.md"),
    `# Archive Index\n\n| # | Title | Tags | Completed | Quarter |\n|---|-------|------|-----------|---------||\n\n*Generated by \`lyt board\`.*\n`,
    options.dryRun,
    result
  );

  // Generate cortex files with examples
  for (const cortexFile of getCortexFiles(options.lang)) {
    writeFile(
      join(lytosDir, "memory", "cortex", cortexFile.name),
      cortexTemplate(cortexFile, options.lang),
      options.dryRun,
      result
    );
  }

  // Write config.yml with user preferences
  writeFile(
    join(lytosDir, "config.yml"),
    `# Lytos configuration\nlanguage: ${options.lang}\nprofile: ${options.profile}\n`,
    options.dryRun,
    result
  );

  // Copy bundled method files (skills, rules, LYTOS.md, templates)
  for (const file of REMOTE_FILES) {
    try {
      const content = readBundled(file.remote);
      writeFile(join(lytosDir, file.local), content, options.dryRun, result);
    } catch (err) {
      result.warnings.push(
        `Could not read bundled file ${file.remote}: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  // Create AI tool config at project root.
  // Each tool has a well-established file-name convention; see the bridge
  // table in README.md / the website compatibility page.
  if (options.tool === "claude") {
    writeFile(
      join(options.cwd, "CLAUDE.md"),
      claudeTemplate(ctx),
      options.dryRun,
      result
    );
  } else if (options.tool === "cursor") {
    writeFile(
      join(options.cwd, ".cursorrules"),
      cursorrTemplate(ctx),
      options.dryRun,
      result
    );
  } else if (options.tool === "codex") {
    writeFile(
      join(options.cwd, "AGENTS.md"),
      codexTemplate(ctx),
      options.dryRun,
      result
    );
  } else if (options.tool === "copilot") {
    // Copilot expects `.github/copilot-instructions.md` (nested — writeFile
    // creates parent dirs).
    writeFile(
      join(options.cwd, ".github", "copilot-instructions.md"),
      copilotTemplate(ctx),
      options.dryRun,
      result
    );
  } else if (options.tool === "gemini") {
    writeFile(
      join(options.cwd, "GEMINI.md"),
      geminiTemplate(ctx),
      options.dryRun,
      result
    );
  } else if (options.tool === "windsurf") {
    writeFile(
      join(options.cwd, ".windsurfrules"),
      windsurfTemplate(ctx),
      options.dryRun,
      result
    );
  }

  // Install git pre-commit hook (branch naming guard)
  const hookResult = installPreCommitHook(options.cwd, options.dryRun);
  if (hookResult === "installed" || hookResult === "dry-run") {
    result.filesCreated.push(join(options.cwd, ".git/hooks/pre-commit"));
  } else if (hookResult === "updated") {
    result.filesCreated.push(join(options.cwd, ".git/hooks/pre-commit"));
  } else if (hookResult === "no-git") {
    result.warnings.push("No .git/ directory found — pre-commit hook not installed. Run `git init` first.");
  }

  return result;
}
